; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_n32r16v]
platform = espressif32
board = esp32s3_n32r16v
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.1
	links2004/WebSockets@^2.7.3
	; arduino-libraries/WiFiNINA@^2.1.1
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 16MB
board_build.partitions = partitions_16MB.csv
